import { defineStore } from 'pinia'
import { tagData } from '@/api/dataInterfaces'
import type { tag } from '@/api/dataInterfaces'

export const useCommonStore = defineStore('common', {
  state: () => {
    return {
      formatList: [
        { value: "CD",  name: "CD"}, 
        { value: "黑胶",  name: "vinyl"}, 
        { value: "磁带",  name: "cassette"}, 
        { value: "数字版",  name: "digital"}, 
        { value: "其他",  name: "other"}
      ],
      formList: [
        { value: "全长专辑" , name: "LP" }, 
        { value: "迷你专辑" , name: "EP" }, 
        { value: "单曲" , name: "single" }, 
        { value: "合作/合辑" , name: "cooperation" }, 
        { value: "其他" , name: "other" }
      ],
      countryList: [
        "US",
        "Andorra",
        "United Arab Emirates",
        "Afghanistan",
        "Antigua and Barbuda",
        "Albania",
        "Armenia",
        "Angola",
        "Argentina",
        "Austria",
        "Australia",
        "Aruba",
        "Azerbaijan",
        "Bosnia and Herzegovina",
        "Barbados",
        "Bangladesh",
        "Belgium",
        "Burkina Faso",
        "Bulgaria",
        "Bahrain",
        "Burundi",
        "Benin",
        "Bermuda",
        "Brunei",
        "Bolivia",
        "Brazil",
        "Bahamas",
        "Bhutan",
        "Botswana",
        "Belarus",
        "Belize",
        "Canada",
        "Democratic Republic of the Congo",
        "Central African Republic",
        "Democratic Republic of the Congo",
        "Switzerland",
        "Chile",
        "Cameroon",
        "China",
        "Colombia",
        "Costa Rica",
        "Cuba",
        "Cape Verde",
        "Cyprus",
        "Czech Republic",
        "Germany",
        "Djibouti",
        "Denmark",
        "Dominica",
        "Dominican Republic",
        "Algeria",
        "Ecuador",
        "Estonia",
        "Egypt",
        "Eritrea",
        "Spain",
        "Ethiopia",
        "Finland",
        "Fiji",
        "Falkland Islands",
        "Micronesia",
        "Faroe Islands",
        "France",
        "Gabon",
        "UK",
        "Grenada",
        "Georgia",
        "Ghana",
        "Gibraltar",
        "Gambia",
        "Guinea",
        "Equatorial Guinea",
        "Greece",
        "Guatemala",
        "Guinea-Bissau",
        "Guyana",
        "Hong Kong",
        "Honduras",
        "Croatia",
        "Haiti",
        "Hungary",
        "Indonesia",
        "Ireland",
        "Israel",
        "India",
        "Iraq",
        "Iran",
        "Iceland",
        "Italy",
        "Jamaica",
        "Jordan",
        "Japan",
        "Kenya",
        "Kyrgyzstan",
        "Cambodia",
        "Kiribati",
        "Comoros",
        "Saint Kitts and Nevis",
        "North Korea",
        "South Korea",
        "Kuwait",
        "Cayman Islands",
        "Kazakhstan",
        "Laos",
        "Lebanon",
        "Saint Lucia",
        "Liechtenstein",
        "Sri Lanka",
        "Liberia",
        "Lesotho",
        "Lithuania",
        "Luxembourg",
        "Latvia",
        "Libya",
        "Morocco",
        "Monaco",
        "Moldova",
        "Montenegro",
        "Madagascar",
        "Macedonia",
        "Mali",
        "Myanmar",
        "Mongolia",
        "Macao",
        "Mauritania",
        "Malta",
        "Mauritius",
        "Maldives",
        "Malawi",
        "Mexico",
        "Malaysia",
        "Mozambique",
        "Namibia",
        "Niger",
        "Nigeria",
        "Nicaragua",
        "Netherlands",
        "Norway",
        "Nepal",
        "Nauru",
        "New Zealand",
        "Oman",
        "Panama",
        "Peru",
        "Papua New Guinea",
        "Philippines",
        "Pakistan",
        "Poland",
        "Puerto Rico",
        "Palestine",
        "Portugal",
        "Palau",
        "Paraguay",
        "Qatar",
        "Romania",
        "Serbia",
        "Russia",
        "Rwanda",
        "Saudi Arabia",
        "Solomon Islands",
        "Seychelles",
        "Sudan",
        "Sweden",
        "Singapore",
        "Slovenia",
        "Slovak Republic",
        "Sierra Leone",
        "San Marino",
        "Senegal",
        "Somalia",
        "Suriname",
        "Sao Tome and Principe",
        "El Salvador",
        "Syria",
        "Swaziland",
        "Chad",
        "Togo",
        "Thailand",
        "Tajikistan",
        "Turkmenistan",
        "Tunisia",
        "Tonga",
        "Turkey",
        "Trinidad and Tobago",
        "Tuvalu",
        "Taiwan",
        "Tanzania",
        "Ukraine",
        "Uganda",
        "Uruguay",
        "Uzbekistan",
        "Saint Vincent And The Grenadine",
        "Venezuela",
        "British Virgin Islands",
        "Vietnam",
        "Vanuatu",
        "Wallis and Futuna",
        "Western Samoa",
        "Yemen",
        "South Africa",
        "Zambia",
        "Zimbabwe"
      ],
      decadeList: [
        { value: "2020s", name: "2020" },
        { value: "2010s", name: "2010" },
        { value: "2000s", name: "2000" },
        { value: "1990s", name: "1990" },
        { value: "1980s", name: "1980" },
        { value: "1970s", name: "1970" },
        { value: "1960s", name: "1960" },
        { value: "1950s", name: "1950" },
        { value: "1940s", name: "1940" },
        { value: "1930s", name: "1930" },
        { value: "1920s", name: "1920" },
        { value: "1910s", name: "1910" },
        { value: "1900s", name: "1900" },
        { value: "1890s", name: "1890" },
        { value: "1880s", name: "1880" },
        { value: "更早", name: "0" }
      ]
    }
  },
  getters: {
    formatTagList(state) {
      return state.formatList.map((format) => {
        return { value: format.value, name: format.name, data: tagData.format }
      })
    },
    formTagList(state) {
      return state.formList.map((form)=> {
        return {value: form.value, name: form.name, data: tagData.form}
      })
    },
    countryTagList(state) {
      return state.countryList.map((country: string) => {
        return { value: country, data: tagData.country }
      })
    },
    decadeTagList(state) {
      return state.decadeList.map((decade) => {
        return { value: decade.value, name: decade.name, data: tagData.decade }
      })
    }
  },
  actions: {

  }
})
