server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: cherry114514
    username: root
  redis:
    host: 127.0.0.1
    port: 6379
#    password:
    database: 0
    lettuce:
      pool:
        max-active: 8
        ##连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        ##连接池最大空闲连接
        max-idle: 8
        ##连接池最小空闲连接
        min-idle: 0
  level:
    root: info
    com:
      example:
        project:
          dao:
            ReleaseDAO: debug
  servlet:
    multipart:
      max-file-size: 5MB
mybatis:
  mapper-locations: classpath:com/example/project/dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
project:
  filePath:
    imgPath: C:\Users\86130\Desktop\project\java\file\img\
logging:
  level:
    com:
      test: debug